//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SESServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayoffBankAccount
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CreatedBy_Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ApprovedBy_Id { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CreatedByEntity_Id { get; set; }
        public string CreatedByUsername { get; set; }
        public Nullable<System.Guid> ApprovedByEntity_Id { get; set; }
        public string ApprovedByUsername { get; set; }
        public PayoffAccountStatusEnum Status { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
        public string BankName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    }
}
