//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SESServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayoffBankAccountsHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid PayoffBankAccountId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> UserProfileId { get; set; }
        public string Username { get; set; }
        public Nullable<System.Guid> EntityId { get; set; }
        public string EntityName { get; set; }
    
        public virtual PayoffBankAccount PayoffBankAccount { get; set; }
    }
}
