//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SESServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayoffBankAccount
    {
        public System.Guid Id { get; set; }
        public System.Guid CreatedBy_Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ApprovedBy_Id { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool IsActive { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AccountInfo_AccountNumber { get; set; }
        public string AccountInfo_RoutingNumber { get; set; }
        public string AccountInfo_BankName { get; set; }
        public string AccountInfo_BankIdentifier { get; set; }
        public string AccountInfo_BankAddress_Address1 { get; set; }
        public string AccountInfo_BankAddress_Address2 { get; set; }
        public string AccountInfo_BankAddress_City { get; set; }
        public string AccountInfo_BankAddress_State { get; set; }
        public string AccountInfo_BankAddress_Zip { get; set; }
    }
}
