//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SESServices.Models
{
    using System;
    
    public enum PayoffAccountStatusEnum : int
    {
        Inactive = 0,
        Active = 1,
        PendingApproval = 2
    }
}
